# placeholder for secrets
[r2]
type = s3
provider = Cloudflare
access_key_id = <access key id>
secret_access_key = <secret access key>
endpoint = https://<account_id>.r2.cloudflarestorage.com

[music]
type = crypt
remote = r2:media/music
filename_encryption = standard
directory_name_encryption = true
password = <crypt password>
password2 = <crypt salt>