name: build
on:
  schedule:
    - cron:
        "00 07 * * *" # build at 06:00 UTC every day
        # (1 hour after secureblue starts building)
  push:
    paths-ignore:
      - "**.md"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  squall-local:
    name: Build Squall
    permissions:
      contents: read # needed to pull repo
      actions: read # needed for provenance verification
      packages: write # needed to publish image
      id-token: write # needed for signing
    uses: ./.github/workflows/build-recipe.yml
    with:
      recipe: squall-local.yml
